### ISSUE TITLE
"Failed to get oplog status." error under high oplog pressure

### ISSUE THREAD

**Issue by timvaillancourt** [Percona-Lab/prometheus_mongodb_exporter#9]
mongodb_exporter outputs the following error under high oplog pressure (very high insert/update tests).

"E0504 18:31:11.270167    3301 oplog_status.go:111] Failed to get oplog status."

Perhaps this should be expected temporarily or something needs optimisation.

Tim

**Comment by dbmurphy** [comment]
Is there some more data you can provide around what condition is failing and cause this  "Failed to get oplog status" result?

A test case and hypothesis on why its occurs would be great

**Comment by timvaillancourt** [comment]
Hi David, I think the issue is the aggregate function I used to get the min/max timestamps. As we discussed, this is heavier than 2 x point queries. I  have an extremely small oplog (for dev testing) of 50mb, so it's possible that contributed to the problem.

The fixes in #12 should repair these problems. I'll leave this open for a few weeks of testing before closing.
